/*	
anchor functionality enhancements
more information/downloads available at: http://uitools.cashmusic.org

distributed under the BSD license
Copyright (c) 2009, CASH Music
All rights reserved.
*/
var CUILinkExternal=new Class({initialize:function(){this.name="linkexternal";this.version=1.1;},attachToElement:function(a){a.removeEvents("click");a.addEvent("click",function(c){var b=a.getProperty("href");c.stop();window.open(b,"cui_"+$random(10000,99999));});}});var CUILinkPopup=new Class({initialize:function(){this.name="linkpopup";this.version=1;this.openoptions="width=480,height=320,scrollbars=yes,resizable=yes,location=no,directories=no,status=no";},attachToElement:function(c){var b=c.getProperty("rev"),a=this.openoptions;c.removeEvents("click");if(b){if(b.contains("popup:")){a=b.substring(6,b.length);}}c.addEvent("click",function(f){var d=c.getProperty("href");f.stop();window.open(d,"cui_external"+$random(10000,99999),a);}.bind(this));}});var CUILinkInside=new Class({initialize:function(){this.name="linkinside";
this.version=1.1;},attachToElement:function(a){a.removeEvents("click");a.addEvent("click",function(i){i.stop();var h="",f="",d=a.getProperty("href"),g=a.getProperty("rev"),j=false,c,b;if(d.contains("?")){h=d.split("?")[1];d=d.split("?")[0];}if(g){if(g.contains("linkinside:")){$A(g.substring(11,g.length).split(",")).each(function(e){c=e.split("=");if(c[0]=="target"){f=c[1];}});}if(f=="parent"){j=true;}else{if(!f){f=document.id(f);}}}if(!f||f=="parent"){f=document.id(a.getParent());if(!j){while(f.getTag()!="div"){f=f.getParent();}}}b=new Request.HTML({url:d,update:f,data:h,onSuccess:function(){if(this.cuiCore){this.cuiCore.htmlContentChanged(f);}}.bind(this)}).get();}.bind(this));}});var CUIDrawer=new Class({Implements:Options,options:{closeOnAttach:false},initialize:function(a){this.name="drawer";
this.version=1;this.setOptions(a);},closedrawer:function(a){a.setStyle("height",1);a.setStyle("display","none");a.store("CUIDrawer_state",1);},toggle:function(a){var b;if(a.retrieve("CUIDrawer_state")==11){b=a.getScrollSize().y;a.store("CUIDrawer_state",10);a.setStyle("height",b);a.get("tween",{property:"height",duration:400}).start(b,1).chain(function(){a.setStyle("display","none");a.store("CUIDrawer_state",1);}.bind(this));}else{if(a.retrieve("CUIDrawer_state")==1){a.store("CUIDrawer_state",10);a.setStyle("display","block");b=a.getScrollSize().y;a.get("tween",{property:"height",duration:400}).start(1,b).chain(function(){a.setStyle("height","auto");a.store("CUIDrawer_state",11);}.bind(this));}}},attachToElement:function(d){var c=d.getProperty("rev"),b=false,g=false,e=false,a;if(c){if(c.contains("drawer:")){$A(c.substring(7,c.length).split(",")).each(function(h){splitArgument=h.split("=");
if(splitArgument[0]=="target"){b=document.id(splitArgument[1]);}else{if(splitArgument[0]=="hideLink"&&splitArgument[1]){g=splitArgument[1];}else{if(splitArgument[0]=="altLinkText"&&splitArgument[1]){e=splitArgument[1];}}}});}if(b){var f=b.getStyle("position");if(f!="absolute"||f!="relative"){b.setStyles({position:"relative",overflow:"hidden"});}else{b.setStyle("overflow","hidden");}if(e){b.store("CUIDrawer_altText",e);}d.removeEvents("click");d.setStyle("cursor","pointer");if(b.currentStyle){a=b.currentStyle.display;}else{a=document.defaultView.getComputedStyle(b,null);if(a!==null){a=a.getPropertyValue("display");}else{a="none";}}if(a=="none"){this.closedrawer(b);}else{b.store("CUIDrawer_state",11);if(this.options.closeOnAttach){this.toggle(b);}}d.addEvent("click",function(i){var h;i.stop();
this.toggle(b);h=b.retrieve("CUIDrawer_altText");if(h){b.store("CUIDrawer_altText",d.get("html"));d.set("html",h);}if(g){d.setStyle("display","none");}}.bind(this));}else{if(this.debugMsg){this.debugMsg(1,"invalid target specified");}}}else{if(this.debugMsg){this.debugMsg(1,'a target must be specified (rev="drawer:target=elementId") with a toggle anchor');}}}});window.addEvent("domready",function(){if(typeof(cashuid)=="object"){cashuid.registerModule(CUILinkExternal,"linkexternal");cashuid.registerModule(CUILinkPopup,"linkpopup");cashuid.registerModule(CUILinkInside,"linkinside");cashuid.registerModule(CUIDrawer,"drawer");}else{var c=new CUILinkExternal(),d=new CUILinkPopup(),a=new CUILinkInside(),b=new CUILinkInside();$$("a.external").each(function(e){c.attachToElement(e);});$$("a.popup").each(function(e){d.attachToElement(e);
});$$("a.cui_linkinside").each(function(e){a.attachToElement(e);});$$("a.cui_drawertoggle").each(function(e){b.attachToElement(e);});}});